In [1]:
import numpy as np

x = np.linspace(0, 2*np.pi, 8)
y = np.sin(x) + np.random.normal(0, 0.4, 8)

In [2]:
x

array([0.        , 0.8975979 , 1.7951958 , 2.6927937 , 3.5903916 ,
       4.48798951, 5.38558741, 6.28318531])

In [4]:
x = x.reshape(-1, 1)

In [5]:
x

array([[0.        ],
       [0.8975979 ],
       [1.7951958 ],
       [2.6927937 ],
       [3.5903916 ],
       [4.48798951],
       [5.38558741],
       [6.28318531]])

In [3]:
y

array([-0.27356381,  1.54394232,  1.04014144,  0.0799363 , -0.65620749,
       -0.97506931, -1.38840701,  0.11483755])